# Generated by Django 4.2.5 on 2023-09-09 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeereport',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.employeereport'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='group',
            field=models.TextField(default='A'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
