# Generated by Django 4.2.5 on 2023-09-09 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_employee_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_reports', to='payroll.employeereport'),
        ),
    ]
